### ISSUE TITLE
Detailed Vehicle Descriptions in App

### ISSUE THREAD

**Issue by Mrsaiba** [realitymod/prspy_app#22]
**Problem**

Currently, it can be confusing and difficult to remember which vehicles in the game are designed for One man. Without clear information about the allowed number of seats and crew members, players may mistakenly choose vehicles that require a team effort to operate effectively. Some players still get confused with the vehicle types.

**Description**

I would like to contribute to the addition of detailed vehicle descriptions within the Project Reality App. This feature would provide users with important information about each vehicle in the game, including allowed seats for passengers and crew, strengths and weaknesses, and the number of ammunition and ammunition type. When the user goes into map view and checks the assets, they can check their description of each vehicle.

**Benefits**

-**Improved user experience**: Users can access comprehensive vehicle information directly within the app, eliminating the confusion and difficulty of remembering which vehicles are suitable for solo players.

- **Enhanced decision-making**: Players can make more informed decisions by understanding each vehicle's capabilities, limitations, and strategic value.

- **Immersive gameplay:** Detailed vehicle descriptions contribute to a stronger sense of immersion, making the gaming experience more engaging.

**Proposed Implementation**

-Vehicle Name: Display the name of the vehicle prominently.
-Description: Provide a concise paragraph describing the vehicle, its role.
-Allowed Seats: Specify the total number of seats
-Passenger Seats: Specify the number of seats available for passengers.
-Crew Seats: Specify the number of seats available for the vehicle's crew.
-Strengths: Enumerate the vehicle's key strengths or advantages.
-Weaknesses: List the vehicle's vulnerabilities or disadvantages.
-Ammunition: Indicate the number of ammunition rounds or types available.

**Additional Notes**

I believe this feature would greatly benefit both new and experienced players, addressing the confusion and providing essential information to make tactical decisions and immerse themselves in the game world. Thank you for considering this feature request, and I look forward to contributing or seeing it implemented in a future update release of the Project Reality App.

Regards, 
a PR Player

**Comment by Alvarocda** [comment]
Hello, thanks for your suggestion.
I believe all this information you requested can be found on the game's wiki

https://projectreality.fandom.com/wiki/ProjectReality_Wiki


Specific link about the vehicles
https://projectreality.fandom.com/wiki/Vehicles

**Comment by Mrsaiba** [comment]
Yes, I know that the information is available for users. 
My suggestion is that to make the app more effective, we can add description in the app itself.

https://i.imgur.com/FolRR1u.jpg

like here in the asset page, there is no description for any vehicles. 
So, when somebody clicks on any asset icon it will expand itself or open a new window showing it's description. 
Like for example,

https://i.imgur.com/IeLPkft.png

so here, the user whenever clicks on the asset he can see the description.
I think it will be great help to the users, as they they don't have to remember everything they just can come and check the app for information. And if somebody needs information about something when in game, i think this is much more feasible then minimizing the game and searching it on the wiki.

And for new players they don't have to search everywhere, they can get the information in the app.
And sorry for the bad design i am not very good at designing :)

**Comment by Alvarocda** [comment]
I understand, however I believe that your request is almost impossible to implement for the following reasons.

1. I myself don't know all this information about all the assets;
2. Even the game's Wiki is outdated;
3. There is not (at least I don't know of) a place where the app can access and fetch this information (API) to display it;

If you are willing to compile all this information, I can prepare the app to display it or i can accept your pull request if you are interested in programming this in the app..

**Comment by Mrsaiba** [comment]
Yes I am willing and I can compile all the data but i need sometime as i have my exams near, so i won't be able to gather them now for 2 months because of my exams.

I am not a flutter developer, I just started learning Andriod Studio now so i don't think i will be of much help in programming the app, but I will try to code it if possible.

I will use these structure while collecting the data

-Vehicle Name: Display the name of the vehicle prominently.
-Description: Provide a concise paragraph describing the vehicle, its role.
-Allowed Seats: Specify the total number of seats
-Passenger Seats: Specify the number of seats available for passengers.
-Crew Seats: Specify the number of seats available for the vehicle's crew.
-Strengths: Enumerate the vehicle's key strengths or advantages.
-Weaknesses: List the vehicle's vulnerabilities or disadvantages.
-Ammunition: Indicate the number of ammunition rounds or types available.

I can do this after 2 months so can you hold that long??

**Comment by Alvarocda** [comment]
Yes, no rush, you can focus on your exams, no problem.

In the meantime, I'm going to create a standardized template so you can compile the information the way the app will consume it based on this structure:

> -Vehicle Name: Display the name of the vehicle prominently.
> -Description: Provide a concise paragraph describing the vehicle, its role.
> -Allowed Seats: Specify the total number of seats
> -Passenger Seats: Specify the number of seats available for passengers.
> -Crew Seats: Specify the number of seats available for the vehicle's crew.
> -Strengths: Enumerate the vehicle's key strengths or advantages.
> -Weaknesses: List the vehicle's vulnerabilities or disadvantages.
> -Ammunition: Indicate the number of ammunition rounds or types available.

**Comment by Mrsaiba** [comment]
Yup, thanks mate.

**Comment by Mrsaiba** [comment]
yup thanks, 
and do you have discord or something else where i can connect with you.

**Comment by Alvarocda** [comment]
> yup thanks, and do you have discord or something else where i can connect with you.


Discord
Álvaro Claro#2083
